apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: c8pm18d64-go 
  janus-idp.io/tekton: c8pm18d64-go
  backstage.io/kubernetes-id: c8pm18d64-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c8pm18d64-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml