apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c8pm18d64-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c8pm18d64-go 
  name: c8pm18d64-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c8pm18d64-go 
